kind: pipeline
name: default

type: docker
steps:
  - name: test
    image: python:3.7-alpine
    commands:
      - pip install -r requirements.txt
      - pytest
  - name: pypi_publish
    image: plugins/pypi
    settings:
      username:
        from_secret: PYPI_LOGIN
      password:
        from_secret: PYPI_PASSWORD
      setupfile: setup.py
